---
language: ruby
bundler_args: --without development
before_install:
  - rm Gemfile.lock || true
  - gem update bundler
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.8.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
matrix:
  exclude:
